import os

SECRET_KEY = os.environ.get('SECRET_KEY')
SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = os.environ.get(
    'SQLALCHEMY_TRACK_MODIFICATIONS')
ADMIN_USERNAME = os.environ.get('ADMIN_USERNAME')
ADMIN_PASWORD = os.environ.get('ADMIN_PASSWORD')
SIMPLEMDE_JS_IIFE = os.environ.get('SIMPLEMDE_JS_IIFE')
SIMPLEMDE_USE_CDN = os.environ.get('SIMPLEMDE_USE_CDN')
