import os

# SECRET KEY
SECRET_KEY = os.environ.get('SECRET_KEY')

# DATABASE STRUFF
SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = os.environ.get(
    'SQLALCHEMY_TRACK_MODIFICATIONS')
ADMIN_USERNAME = os.environ.get('ADMIN_USERNAME')
ADMIN_PASWORD = os.environ.get('ADMIN_PASSWORD')

# SIMPLE MDE CONFIGURATION
SIMPLEMDE_JS_IIFE = os.environ.get('SIMPLEMDE_JS_IIFE')
SIMPLEMDE_USE_CDN = os.environ.get('SIMPLEMDE_USE_CDN')

# MAIL CONFIGURATION
MAIL_SERVER = 'smtp.mailtrap.io'
MAIL_PORT = 2525
MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
MAIL_USE_TLS = True
MAIL_USE_SSL = False
