"""empty message

Revision ID: 360ea7828c19
Revises: 
Create Date: 2020-05-25 14:08:20.551549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360ea7828c19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('privacy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'privacy')
    # ### end Alembic commands ###
