"""Switch to Flask-WTF

Revision ID: 457314b20e4a
Revises: e729a6a45960
Create Date: 2020-06-07 15:54:26.530995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457314b20e4a'
down_revision = 'e729a6a45960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notes', 'user', ['owner_id'], ['id'])
    op.add_column('user', sa.Column('name', sa.String(length=50), ))
    op.add_column('user', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website')
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    # ### end Alembic commands ###
