"""empty message

Revision ID: a39531d04df0
Revises: 457314b20e4a
Create Date: 2020-06-08 20:26:47.252468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39531d04df0'
down_revision = '457314b20e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        # batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])
        batch_op.create_foreign_key('owner_id', 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), ))
        batch_op.add_column(
            sa.Column('website', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('name')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
